### ISSUE TITLE
running simulator file

### ISSUE THREAD

**Issue by siuolkl** [ScarredMonk/SysmonSimulator#1]
Hi how do i run the simulator file ?  c file ?
![image](https://user-images.githubusercontent.com/96816514/149626215-8600e9fd-662d-4805-a9cd-d6ad2df3036c.png)

**Comment by ScarredMonk** [comment]
Hey siuolkl, 

To generate the executable, you can perform below steps:

1. Clone the Git repository or download the zip.
2. Open the SysmonSimulator.sln in Visual Studio. 
3. Go to Build>Build Solution.

That will build the solution and SysmonSimulator.exe will be created.

![SysmonSimulatorInstructions](https://user-images.githubusercontent.com/46210620/149630682-5f58029b-cc62-403f-bc3b-73075b1f9d83.png)
