### ISSUE TITLE
SysmonSimulator.exe is missing 

### ISSUE THREAD

**Issue by dordor89** [ScarredMonk/SysmonSimulator#2]
Hey,

there is a plan to upload SysmonSimulator.exe again?

thanks

**Comment by AndrewRathbun** [comment]
See here: https://github.com/ScarredMonk/SysmonSimulator/issues/1

**Comment by ScarredMonk** [comment]
Hi @dordor89 

This has been added in the releases

**Comment by dordor89** [comment]
hey,

thanks a lot.
