### ISSUE TITLE
Consider removing interactivity requirement for process terminate and process access events

### ISSUE THREAD

**Issue by dstaulcu** [ScarredMonk/SysmonSimulator#3]
Consider removing interactivity requirement for process terminate and process access events

instead of prompting for ID of process to terminate or access just create a new and hidden notepad instance and operate on that instance.

this code is super helpful not just for learning but also for load and unit testing new sysmon releases.  Thank you!

**Comment by ScarredMonk** [comment]
Hey @dstaulcu 

Thanks for the suggestion. This has been done. 

![image](https://user-images.githubusercontent.com/46210620/150244877-9cf064e5-f54b-4319-8cc8-8b30933d0a91.png)

Added the new code and executable in releases
